# This is the inner config used by the bot, it'll be automatically modified once the setup is run.

grinderConfig:
  - channel: # The channel you want the bot to run commands in
  - type: #levels/money: Whether the bot should grind mainly for growth in money, or for growth in levels
  - usePercentage: # Percentage between 1-100%, how much money the bot can use for itself, ex - To buy items when they break, livesavers, etc.

sell:
  - sellItems: #true/false: Whether or not the bot should sell items in its inventory, ex - Fish (from fishing), items (from scouting), etc.
  - doNotSell: [] # a list of item names to not sell

money:
  - transfer: # true/false: whether or not the bot should transfer funds periodically to its owner
  - owner: # The user ID of the person the bot should transfer funds to
